### ISSUE TITLE
Agilicious Submodule

### ISSUE THREAD

**Issue by razarcon3** [ctu-mrs/pmm_uav_planner#2]
In the paper it mentions you use a nonlinear MPC controller to track the trajectory generated by your PMM planner. It looks like you've included agilicious as a submodule so I'm assuming you are using their MPC controller implementation?

**Comment by novosma** [comment]
Ahh, sorry about that and thank you for pointing it out. It is a leftover from a really early phase of development. I have removed it from the repository.

We do don't use agilicious at all. We use MRS system (https://github.com/ctu-mrs/mrs_uav_system), and our own implementation of nonlinear MPC controller, which we plan to publish in near future.

We have not tested it, yet we assume agilicious solution could probably also be used, but some output csv adjustments might be necessary.

**Comment by KennethYangle** [comment]
Hi! Could you share which open-source project, if any, the nonlinear MPC is based on? Looking forward to seeing your upcoming publication!

**Comment by novosma** [comment]
Hi, sorry for getting to you so late... The MPC we used for experiments in this paper is based on before mentioned [agilicious](https://github.com/uzh-rpg/agilicious) , which was also used in Philipp Foehn et al. Time-optimal planning for quadrotor waypoint flight. Sci. Robot.6,eabh1221(2021). DOI:[10.1126/scirobotics.abh1221](https://doi.org/10.1126/scirobotics.abh1221).

We plan to open-source our implementation together with the publication, as it will also feature some another, novel approach, still WIP though. So keep an eye out for that!

**Comment by KennethYangle** [comment]
Thank you for clarifying. I will give Agilicious a try myself. Looking forward to seeing your work published!
